name: Deploy goals API

on:
  workflow_dispatch:

jobs:
  pipeline:
    uses: IDEMSInternational/parenttext-goals-webhooks/.github/workflows/deploy.yml@c1db31107c4898ace2813f63ab504afe4b5c5a68
    secrets:
      credentials: ${{ secrets.GCP_CREDENTIALS }}
    with:
      image: ${{ vars.GOALS_API_IMAGE }}
      region: ${{ vars.GCP_REGION }}
      service_env: ${{ vars.GCP_SERVICE_ENV }}
      service_identity: ${{ vars.GCP_SERVICE_IDENTITY }}
      service_name: ${{ vars.GCP_SERVICE_NAME }}